name: Build Android APK

on:
  push:
    branches: [ main, master ] # Triggers whenever you push code

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Set up Java 21 Engine
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Setup Gradle Cache
      uses: actions/setup-gradle@v4

    - name: Grant execute permission for gradlew
      run: chmod +x android/gradlew

    - name: Build Standalone Debug APK
      run: |
        cd android
        ./gradlew assembleDebug

    - name: Upload Finished APK
      uses: actions/upload-artifact@v4
      with:
        name: safepass-debug-apk
        path: android/app/build/outputs/apk/debug/app-debug.apk